version: '3'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDByduqs!
      MONGO_INITDB_DATABASE: auraEntregas
    ports:
      - '27017:27017'
